### ISSUE TITLE
[Correção manual de qualidade]

### ISSUE THREAD

**Issue by DiogoBranda** [DiogoBranda/Low-cost-sensor-modules-for-ocean-exploration#2]
- [x] Acrescentar sumario executivo  antes da introdução
- [x] Dizer quando o documento vai ser revisto
- [x] Criar subsecção para explicar a logica de organização por cargos
- [x] Colocar procedimentos depois da organização da equipa 
- [x] Gestão de riscos é só dizer o que vai ser adicionado no manual de qualidade mais tarde porque ainda não demos nas teóricas(Deixámos estar?)
- [x] Gestão de conflitos passar para dentro dos procedimentos ou ser secção a parte
- [x] Se acharmos útil podemos colocar explicação de acrónimos, caso contrario colocar em próximos documentos.
considerar usar milestones 
- [x] Explicar quem convoca a reunião, como são convocadas, quem conduz a reunião e minutas.
- [x] Controlo comportamental explicar na parte do moderador 
- [x] Avaliação como decorre? no fim faz-se a media?

**Comment by DiogoBranda** [comment]
Coloquei o texto que explica como esta a hierarquia dos cargos

**Comment by margaridasantiago** [comment]
Falta rever o sumario executivo, não sei o quanto detalhado tem de ser mas vejam e se quiserem acrescentar cenas feel free
