### ISSUE TITLE
[Market Survey] - Pesquisa

### ISSUE THREAD

**Issue by DiogoBranda** [DiogoBranda/Low-cost-sensor-modules-for-ocean-exploration#4]
Devem adicionar artigos que achem interessantes no git. Depois teremos uma pasta em que teremos toda a pesquisa.

Tópicos de pesquisa

-dropcams
-harvesting de energia? tipo através de temperatura perto de fontes hidrotermais
-conectores para permanecer estanque (formas de transferir informação e energia para dentro/fora do sistema mas que não permitam entrar água)
-câmaras
-sensores
-como volta do fundo? sistemas de recuperação (alguns exemplos são acoustic release e  burn-wire, um sistema com que quando uma pilha entra em contacto com um fio de cobre este desfaz-se e permite que a caixa volte à superfície)
-Gestão ativa de potência
-Interface com sensores
-Sistemas low power
-Sistemas de baixo custo que possam ser colocados no fundo do mar

**Comment by margaridasantiago** [comment]
exemplo artigo sobre HydroNodes capazes de acoplar diferentes sensores para exploração do oceano, caracteristicas como: low cost, energy efficient 
[sens_HydroNode.pdf](https://github.com/DiogoBranda/Low-cost-sensor-modules-for-ocean-exploration/files/5373390/sens_HydroNode.pdf)

**Comment by DiogoBranda** [comment]
Coloquei na branch pesquisa. E adicionei os dois que ja tinha encontrado sobre low-power systems. Adicionem sempre lá, avisem aqui que colocaram para todos receberem a notificação 

> exemplo artigo sobre HydroNodes capazes de acoplar diferentes sensores para exploração do oceano, caracteristicas como: low cost, energy efficient
> [sens_HydroNode.pdf](https://github.com/DiogoBranda/Low-cost-sensor-modules-for-ocean-exploration/files/5373390/sens_HydroNode.pdf)

**Comment by DiogoBranda** [comment]
Alterei isto e agora a pesquisa esta dentro de documentos. Fica mais fácil

**Comment by hugofariapires** [comment]
Adicionei um sobre acoustic release
